language: java
jdk: openjdk11

branches:
  only:
    - dev

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw clean package -B

after_success:
  - docker build -t scenecho/dinner -f Dockerfile.dev ./
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push scenecho/dinner

notifications:
  email:
    recipients:
      - scene_cho@naver.com
